import { fileURLToPath } from "node:url";

import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig, lazyPlugins } from "vite-plus";
import { configDefaults } from "vite-plus";

export default defineConfig({
  fmt: {},
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react"],
    jsPlugins: [
      "@eslint-react/eslint-plugin",
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
    categories: {
      correctness: "warn",
    },
    env: {
      builtin: true,
      browser: true,
      node: true,
    },
    settings: {
      "react-x": {
        version: "detect",
        importSource: "react",
        polymorphicPropName: "as",
      },
    },
    ignorePatterns: ["dist", ".wrangler", ".delta"],
    rules: {
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-const-assign": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-empty-static-block": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-new-native-nonconstructor": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-obj-calls": "error",
      "no-prototype-builtins": "error",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-self-assign": "error",
      "no-setter-return": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-this-before-super": "error",
      "no-unassigned-vars": "error",
      "no-undef": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": "error",
      "no-useless-assignment": "error",
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-with": "error",
      "preserve-caught-error": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "no-array-constructor": "error",
      "no-unused-expressions": "error",
      "@eslint-react/error-boundaries": "error",
      "@eslint-react/exhaustive-deps": "warn",
      "@eslint-react/no-access-state-in-setstate": "error",
      "@eslint-react/no-array-index-key": "warn",
      "@eslint-react/no-children-count": "warn",
      "@eslint-react/no-children-for-each": "warn",
      "@eslint-react/no-children-map": "warn",
      "@eslint-react/no-children-only": "warn",
      "@eslint-react/no-children-to-array": "warn",
      "@eslint-react/no-clone-element": "warn",
      "@eslint-react/no-component-will-mount": "error",
      "@eslint-react/no-component-will-receive-props": "error",
      "@eslint-react/no-component-will-update": "error",
      "@eslint-react/no-context-provider": "warn",
      "@eslint-react/no-create-ref": "error",
      "@eslint-react/no-direct-mutation-state": "error",
      "@eslint-react/no-forward-ref": "warn",
      "@eslint-react/no-missing-key": "error",
      "@eslint-react/no-nested-component-definitions": "error",
      "@eslint-react/no-nested-lazy-component-declarations": "error",
      "@eslint-react/no-set-state-in-component-did-mount": "warn",
      "@eslint-react/no-set-state-in-component-did-update": "warn",
      "@eslint-react/no-set-state-in-component-will-update": "warn",
      "@eslint-react/no-unnecessary-use-prefix": "warn",
      "@eslint-react/no-unsafe-component-will-mount": "warn",
      "@eslint-react/no-unsafe-component-will-receive-props": "warn",
      "@eslint-react/no-unsafe-component-will-update": "warn",
      "@eslint-react/no-unused-class-component-members": "warn",
      "@eslint-react/no-use-context": "warn",
      "@eslint-react/purity": "warn",
      "@eslint-react/rules-of-hooks": "error",
      "@eslint-react/set-state-in-effect": "warn",
      "@eslint-react/set-state-in-render": "error",
      "@eslint-react/static-components": "error",
      "@eslint-react/unsupported-syntax": "error",
      "@eslint-react/use-memo": "error",
      "@eslint-react/use-state": "warn",
      "@eslint-react/jsx-no-children-prop": "warn",
      "@eslint-react/jsx-no-children-prop-with-children": "error",
      "@eslint-react/jsx-no-comment-textnodes": "warn",
      "@eslint-react/jsx-no-key-after-spread": "error",
      "@eslint-react/jsx-no-leaked-dollar": "warn",
      "@eslint-react/jsx-no-leaked-semicolon": "warn",
      "@eslint-react/jsx-no-namespace": "error",
      "@eslint-react/rsc-function-definition": "error",
      "@eslint-react/dom-no-dangerously-set-innerhtml": "warn",
      "@eslint-react/dom-no-dangerously-set-innerhtml-with-children": "error",
      "@eslint-react/dom-no-find-dom-node": "error",
      "@eslint-react/dom-no-flush-sync": "error",
      "@eslint-react/dom-no-hydrate": "error",
      "@eslint-react/dom-no-render": "error",
      "@eslint-react/dom-no-render-return-value": "error",
      "@eslint-react/dom-no-script-url": "warn",
      "@eslint-react/dom-no-unsafe-iframe-sandbox": "warn",
      "@eslint-react/dom-no-use-form-state": "error",
      "@eslint-react/dom-no-void-elements-with-children": "error",
      "@eslint-react/web-api-no-leaked-event-listener": "warn",
      "@eslint-react/web-api-no-leaked-fetch": "warn",
      "@eslint-react/web-api-no-leaked-intersection-observer": "warn",
      "@eslint-react/web-api-no-leaked-interval": "warn",
      "@eslint-react/web-api-no-leaked-resize-observer": "warn",
      "@eslint-react/web-api-no-leaked-timeout": "warn",
      "@eslint-react/naming-convention-context-name": "warn",
      "@eslint-react/naming-convention-id-name": "warn",
      "@eslint-react/naming-convention-ref-name": "warn",
      "react/rules-of-hooks": "error",
      "react/static-components": "error",
      "react/use-memo": "error",
      "react/void-use-memo": "error",
      "react/preserve-manual-memoization": "error",
      "react/immutability": "error",
      "react/globals": "error",
      "react/refs": "error",
      "react/set-state-in-effect": "error",
      "react/error-boundaries": "error",
      "react/purity": "error",
      "react/set-state-in-render": "error",
      "react/unsupported-syntax": "warn",
      "typescript/ban-ts-comment": "error",
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-empty-object-type": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-extra-non-null-assertion": "error",
      "typescript/no-misused-new": "error",
      "typescript/no-namespace": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-require-imports": "error",
      "typescript/no-this-alias": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "typescript/no-unsafe-declaration-merging": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-wrapper-object-types": "error",
      "typescript/prefer-as-const": "error",
      "typescript/prefer-namespace-keyword": "error",
      "typescript/triple-slash-reference": "error",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    overrides: [
      {
        files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
        rules: {
          "constructor-super": "off",
          "getter-return": "off",
          "no-class-assign": "off",
          "no-const-assign": "off",
          "no-dupe-class-members": "off",
          "no-dupe-keys": "off",
          "no-func-assign": "off",
          "no-import-assign": "off",
          "no-new-native-nonconstructor": "off",
          "no-obj-calls": "off",
          "no-redeclare": "off",
          "no-setter-return": "off",
          "no-this-before-super": "off",
          "no-undef": "off",
          "no-unreachable": "off",
          "no-unsafe-negation": "off",
          "no-var": "error",
          "no-with": "off",
          "prefer-const": "error",
          "prefer-rest-params": "error",
          "prefer-spread": "error",
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  staged: {
    "*.{js,mjs,cjs,jsx,ts,tsx,css,md}": "vp fmt --write",
    "src/**/*.{ts,tsx}": ["vp lint --fix", "vitest related --run"],
  },
  plugins: lazyPlugins(() => [tailwindcss(), react()]),
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  test: {
    // Two environments, told apart by the test file's extension: plain
    // logic runs in node, anything that renders React runs in a DOM.
    // `exclude` does not cascade from here into the projects, so the
    // Playwright suite has to be excluded where the files are matched.
    projects: [
      {
        extends: true,
        test: {
          name: "unit",
          include: ["src/**/*.test.ts"],
          exclude: [...configDefaults.exclude, "e2e/**"],
        },
      },
      {
        extends: true,
        test: {
          name: "dom",
          include: ["src/**/*.test.tsx"],
          environment: "happy-dom",
          // the goatcounter test injects the count script; happy-dom never
          // evaluates external scripts, and the default reports that as an
          // error log per appendChild — disabled loading is instead
          // reported as success, which also fires the script's "load"
          // event the analytics lib flushes queued counts on
          environmentOptions: {
            happyDOM: {
              settings: {
                disableJavaScriptFileLoading: true,
                handleDisabledFileLoadingAsSuccess: true,
              },
            },
          },
          setupFiles: ["./src/test/setup.ts"],
        },
      },
    ],
  },
});
