import { useState } from "react";
import Head from "next/head";

import checkPalindrome from "@/lib/checkPalindrome";

export default function Home() {
  const [value, setValue] = useState("");
  const [{ isPalindrome, mirror, center, normalizedText }, setPali] = useState({
    isPalindrome: false,
    mirror: [],
    center: [],
    normalizedText: "",
  });

  const handleChange = (event) => {
    const text = event.target.value;
    setValue(text);
    setPali(checkPalindrome(text));
  };

  return (
    <div>
      <Head>
        <title>Palindromaker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-3">
        <h1 className="text-2xl">Palindromaker</h1>
        <textarea
          className={`border border-black my-4 ${
            isPalindrome ? "bg-green-200" : "bg-red-200"
          }`}
          value={value}
          onChange={handleChange}
          rows={5}
          cols={50}
        />
        <p>IsPalindrome: {isPalindrome ? "yes" : "NO"}</p>
        <p>{mirror}</p>
        <p>{center}</p>
        <p>{normalizedText}</p>
      </main>
    </div>
  );
}
