import Head from "next/head";

import Editor from "@/components/editor";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Palindromaker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-4">
        <h1 className="text-3xl font-semibold text-gray-900 mb-3">
          Palindromaker
        </h1>

        <Editor />
      </main>
    </div>
  );
}
